--- #YAML:1.0
name:               Net-Twitter
version:            1.20
abstract:           Perl interface to twitter.com
author:
    - Chris Thompson <cpan@cthompson.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    JSON::Any:       0
    LWP::UserAgent:  0
    Test::More:      0
    URI::Escape:     0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.46
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
